### ISSUE TITLE
Versioneer is causing problems with conda build

### ISSUE THREAD

**Issue by sobolevnrm** [Electrostatics/mmcif_pdbx#48]
@orbeckst can you please look at https://github.com/conda-forge/mmcif_pdbx-feedstock/pull/2#issuecomment-774016234 and see if you can help @tsenapathi and me figure out what is going on with versioneer?  Thank you!

**Comment by speleo3** [comment]
I get the same error with `python -m pip install .`, I don't know if versioneer is supposed to support this.

`python setup.py install` works for me.

I don't use versioneer myself, and I usually install stuff with `python setup.py install` instead of `pip`.

**Comment by sobolevnrm** [comment]
I've replaced versioneer in my other code with `importlib`:

https://github.com/Electrostatics/osmolytes/blob/f8ac99827ba199b359ccf141b604a2b7362f9dbf/osmolytes/__init__.py#L12

**Comment by orbeckst** [comment]
It seems that @speleo3 already found  solution – I don't understand why adding PWD to PYTHONPATH is necessary because my understanding was that either `pip install .` or `python setup.py` are run from `setup.py`'s directory and then `import versioneer` in `setup.py` should "just work".

It looked to me that `setup.py` was getting confused about a versioneer module, perhaps because it had been installed. My (limited) understanding of how it works is that it needs to be `versioneer.py` in the same directory as `setup.py` so that it can find https://github.com/Electrostatics/mmcif_pdbx/blob/7de84811e8863b38555b371d1f824473cbb30cf4/versioneer.py#L1536.

For another project the line https://github.com/conda-forge/griddataformats-feedstock/blob/0f4c2d9eb070b9015a295c1eb3c3bee3dcac7639/recipe/meta.yaml#L15 
```yaml
build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
```
(without installing versioneer as a dep) has been working (although that one hasn't run in a while, maybe something change on conda-forge).

**Comment by tsenapathi** [comment]
@sobolevnrm @speleo3 @orbeckst @intendo @rubadub Thank you all build worked with the setup file.
